### ISSUE TITLE
QuantumCircuit seems raise an error for .cnot()

### ISSUE THREAD

**Issue by wjy99-c** [Qiskit/qiskit-metapackage#1118]
### Informations

- **Qiskit version**: Qiskit 0.21.0
- **Python version**: Python 3.8.3
- **Operating system**: MacOS 10.15.7

### What is the current behavior?
I find it raises an exception with ".cnot()." I check the document for ".cnot()" on the Qiskit website and it just says ".cnot()" calls ".cx()", but ".cx()" works totally fine in my code.

### Steps to reproduce the problem
```
def make_circuit(n:int) -> QuantumCircuit:
    # circuit begin
    input_qubit = QuantumRegister(n,"qc")
    classical = ClassicalRegister(n, "qm")
    prog = QuantumCircuit(input_qubit, classical)
    prog.h(0)
    prog.cx(0,1)
    prog.cnot(0,1)
    prog.measure_all()
    # circuit end


    return prog



if __name__ == '__main__':

    prog = make_circuit(3)
    backend = BasicAer.get_backend('qasm_simulator')

    info = execute(prog, backend=backend, shots=1024).result().get_counts()

```
Raise an error as follow:
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py:1817: DeprecationWarning: cx keyword argument ctl is deprecated and replaced with control_qubit.
  self.cx(control_qubit, target_qubit, ctl=ctl, tgt=tgt)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py:1817: DeprecationWarning: cx keyword argument tgt is deprecated and replaced with target_qubit.
  self.cx(control_qubit, target_qubit, ctl=ctl, tgt=tgt)
Traceback (most recent call last):
  File "/Users/a123/Desktop/Qiskit1/cnot.py", line 57, in <module>
    prog = make_circuit(3)
  File "/Users/a123/Desktop/Qiskit1/cnot.py", line 46, in make_circuit
    prog.cnot(0,1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiskit/util.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiskit/circuit/quantumcircuit.py", line 1817, in cnot
    self.cx(control_qubit, target_qubit, ctl=ctl, tgt=tgt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiskit/util.py", line 109, in wrapper
    return func(*args, **kwargs)
TypeError: cx() got multiple values for argument 'control_qubit'
```

### What is the expected behavior?

.cnot() should be the same as .cx().

**Comment by kdk** [comment]
This should be fixed in all qiskit versions >= 0.20  (by https://github.com/Qiskit/qiskit-terra/pull/4713 ). Please re-open if you're still seeing this issue.
