### ISSUE TITLE
Getting instruction schedule map throws results in an exception

### ISSUE THREAD

**Issue by ntwalibas** [Qiskit/qiskit-metapackage#1132]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.7.7
- **Operating system**: MacOS Catalina 10.15.7

### What is the current behavior?
Attempting to get the instruction schedule map from the given backend results in the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqbackend.py", line 305, in defaults
    self._defaults = PulseDefaults.from_dict(api_defaults)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/validation/base.py", line 354, in from_dict
    data = cls.schema.load(dict_)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/marshmallow/schema.py", line 897, in _do_load
    partial=partial,
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/marshmallow/schema.py", line 1098, in _invoke_load_processors
    partial=partial,
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/marshmallow/schema.py", line 1224, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/validation/base.py", line 163, in make_model
    return self.model_cls(**data)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/validation/base.py", line 244, in _decorated
    return init_method(self, **kwargs, validate=False)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/providers/models/pulsedefaults.py", line 149, in __init__
    pulse_insts = [self.converter(inst) for inst in inst.sequence]
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/providers/models/pulsedefaults.py", line 149, in <listcomp>
    pulse_insts = [self.converter(inst) for inst in inst.sequence]
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/qobj/converters/pulse_instruction.py", line 418, in __call__
    return method(self, instruction)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/qobj/converters/pulse_instruction.py", line 606, in convert_parametric
    pulse = ParametricPulseShapes[instruction.pulse_shape].value(**instruction.parameters)
  File "/Users/ntwalibas/miniconda3/envs/openpulse/lib/python3.7/site-packages/qiskit/pulse/pulse_lib/parametric_pulses.py", line 309, in __init__
    self._amp = complex(amp)
TypeError: complex() first argument must be a string or a number, not 'list'
```

### Steps to reproduce the problem

Execute the following code in the your Python REPL:

```
from qiskit import IBMQ
IBMQ.delete_account()
IBMQ.save_account("<YOUR-API-KEY-HERE", overwrite=True)
IBMQ.load_account()
provider = IBMQ.get_provider(
    hub='<your-hub>',
    group='<your-group>',
    project='<your-project>',
)
backend = provider.get_backend('ibmq_casablanca') # I've attempted this on Casablanca but I believe the behaviour is independent of the specific backend
backend.defaults().instruction_schedule_map
```

### What is the expected behavior?
One should get the instruction schedule map without exception (obviously) and without warnings when using the latest version of Qiskit _et al._ 

### Suggested solutions
None

**Comment by ntwalibas** [comment]
Never mind, I hadn't updated my Qiskit version!
