### ISSUE TITLE
Pulse schedule construction benchmarks fail

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-metapackage#1146]
### What is the current behavior?
```
Traceback (most recent call last):
                 File "/usr/lib/python3.8/site-packages/asv/benchmark.py", line 860, in disc_modules
                   module = import_module(module_name)
                 File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                   return _bootstrap._gcd_import(name[level:], package, level)
                 File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                 File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                 File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                 File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                 File "<frozen importlib._bootstrap_external>", line 783, in exec_module
                 File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                 File "/home/mtreinish/git/qiskit/qiskit/test/benchmarks/pulse/schedule_construction.py", line 19, in <module>
                   from qiskit.pulse import Schedule, Gaussian, DriveChannel, SamplePulse, Play
               ImportError: cannot import name 'SamplePulse' from 'qiskit.pulse' (/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/pulse/__init__.py)
```
### Steps to reproduce the problem

Run benchmarks

### What is the expected behavior?

They work

### Suggested solutions
Update for breaking api changes in pulse

**Comment by vishwas1234567** [comment]
Hai, I want to solve this

**Comment by SooluThomas** [comment]
@vishwas1234567 There is already a PR open for fixing this issue - #1147
