### ISSUE TITLE
Qiskit won't import itself.

### ISSUE THREAD

**Issue by ghost** [Qiskit/qiskit-metapackage#1167]
### Informations

- **Qiskit version**: 0.23.5
- **Python version**: 3.7.9
- **Operating system**: Windows familly 10.0.18362

### What is the current behavior?

```
Traceback (most recent call last):
  File "C:/Users/cambi/Documents/Dossier I-Q/Discord/ttest.py", line 1, in <module>
    import qiskit
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\__init__.py", line 57, in <module>
    from qiskit.providers.aer import Aer
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\__init__.py", line 64, in <module>
    from .aerprovider import AerProvider
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\aerprovider.py", line 20, in <module>
    from .backends.qasm_simulator import QasmSimulator
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\backends\__init__.py", line 20, in <module>
    from .pulse_simulator import PulseSimulator
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\backends\pulse_simulator.py", line 26, in <module>
    from ..pulse.controllers.pulse_controller import pulse_controller
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\__init__.py", line 52, in <module>
    from .system_models.duffing_model_generators import duffing_system_model
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\system_models\duffing_model_generators.py", line 21, in <module>
    from .hamiltonian_model import HamiltonianModel
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\system_models\hamiltonian_model.py", line 22, in <module>
    from .string_model_parser.string_model_parser import HamiltonianParser
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\system_models\string_model_parser\string_model_parser.py", line 23, in <module>
    from .qobj_from_string import gen_oper
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\system_models\string_model_parser\qobj_from_string.py", line 18, in <module>
    from ...qutip_extra_lite import qobj_generators
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\qutip_extra_lite\qobj_generators.py", line 19, in <module>
    from . import operators as ops
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\qutip_extra_lite\operators.py", line 56, in <module>
    from .fastsparse import fast_csr_matrix, fast_identity
  File "C:\Users\cambi\AppData\Local\Programs\Python\Python37\lib\site-packages\qiskit\providers\aer\pulse\qutip_extra_lite\fastsparse.py", line 440, in <module>
    from .cy.spmath import (zcsr_transpose, zcsr_adjoint, zcsr_mult)
  File "spmath.pyx", line 1, in init qiskit.providers.aer.pulse.qutip_extra_lite.cy.spmath
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

### Steps to reproduce the problem

launch the code : `import qiskit`

### What is the expected behavior?

Qiskit import itself with no error.

### Suggested solutions

None

**Comment by mtreinish** [comment]
This is a duplicate of Qiskit/qiskit-aer#1120 and is caused by a C api incompatibility in the precompiled binaries released for qiskit-aer with older numpy versions. It should hopefully be fixed by a bugfix release that will be pushed out today or tomorrow, but in the meantime you can upgrade your numpy version to the latest release (or any version >=1.20.0) to workaround this.

**Comment by ghost** [comment]
Thanks for your tip !
