### ISSUE TITLE
'pip install qiskit' not working with python3.7

### ISSUE THREAD

**Issue by daveshen2019** [Qiskit/qiskit-metapackage#187]
### Informations

- **Qiskit version**: latest version
- **Python version**: 3.7
- **Operating system**: windows 10

### What is the current behavior?
I was able to install qiskit successfully while running python 3.6, pip version 10.
However, running python 3.7, and pip 19.3.0.  'pip install qiskit' failed:
"""Collecting qiskit
Could not find a version that satisfies the requirement qiskit-aer==0.1.1 (from qiskit) (from versions: 0.1.0)
No matching distribution found for qiskit-aer==0.1.1 (from qiskit)"""

![pip_install_qiskit](https://user-images.githubusercontent.com/48633747/55275443-5e7e6780-52a3-11e9-8fbf-f647c793f82d.png)

**Comment by daveshen2019** [comment]
I have done the following since I opened this issue:
1. installed the previous python version that worked with qiskit
2. upgrade the pip version to 19
It did not work and produced the same err message.

**Comment by daveshen2019** [comment]
Hi, I spend more time on it, and made some progress:
1. i revert back qiskit from 0.8.0 to 0.7.0.  qiskit 0.7.0 worked.  qiskit 0.8.0 does not (for me)
1. install the individual module separately, and here is the progress:
![image](https://user-images.githubusercontent.com/48633747/55286414-752ec800-5350-11e9-8102-07fb80229fee.png)
the modules in blue color are installed successfully
the modules in black color are failed installation

2. I run all my past IBMQ python code, they all work on qiskit 0.7.0
![qiskit 0 7 0](https://user-images.githubusercontent.com/48633747/55286486-1d449100-5351-11e9-8a2f-6f61197b4ba2.png)
.

**Comment by imv7** [comment]
```  Could not find a version that satisfies the requirement qiskit-aer==0.1.1 (from qiskit) (from versions: 0.1.0)
Cleaning up...
  Removing temporary dir /private/var/folders/_w/_t2gmngn2k3_bmjbk3s9q3tw0000gn/T/pip_build_igor...
No distributions matching the version for qiskit-aer==0.1.1 (from qiskit)
Exception information:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for qiskit-aer==0.1.1 (from qiskit)```
This is the stdout of the same error on my machine ```

IGOR-3:~ root# python
Python 2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> version

**Comment by imv7** [comment]
Mine worked. I had to use the pip from version 3.7.

```7   
IGOR-3:~ igor$ pip
pip      pip-2.7  pip2     pip2.7   pip3     pip3.7   
IGOR-3:~ igor$ pi3.7 install qiskit
-bash: pi3.7: command not found
IGOR-3:~ igor$ pip3.7 install qiskit
Collecting qiskit
  Downloading https://files.pythonhosted.org/packages/37/13/62c8421098faf49cbd380911986b1c9eebead08518084faa9a0dbbfc71c1/qiskit-0.8.0.tar.gz
Collecting qiskit_terra==0.7.1 (from qiskit)
  Downloading https://files.pythonhosted.org/packages/c2/01/cafc66915a227d9f975932086bd31219d8ba71365aa1109bda5a5ebc067a/qiskit_terra-0.7.1-cp37-cp37m-macosx_10_7_x86_64.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 901kB/s 
Collecting qiskit-aer==0.1.1 (from qiskit)
  Downloading https://files.pythonhosted.org/packages/e5/4b/14ce6a34a82d2de50d481a669403a2bfcf3cbcea2ddf2404e76a0390a17e/qiskit_aer-0.1.1-cp37-cp37m-macosx_10_9_x86_64.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 1.1MB/s 
Collecting qiskit-ignis==0.1.0 (from qiskit)
  Downloading https://files.pythonhosted.org/packages/cf/78/9f201689069a599c02d676567b55871104a61169857d7474321426f3d603/qiskit_ignis-0.1.0-py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 1.9MB/s 
Collecting marshmallow<3,>=2.16.3 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/bc/b4/f54f8533aad0645431bfda2cc3d20913a305779c80f8cb71229e8b615c5b/marshmallow-2.19.2-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 2.0MB/s 
Collecting requests-ntlm>=1.1.0 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
Collecting pillow>=4.2.1 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/c9/ed/27cc92e99b9ccaa0985a66133baeea7e8a3371d3c04cfa353aaa3b81aac1/Pillow-5.4.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 1.1MB/s 
Collecting ply>=3.10 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 2.0MB/s 
Collecting jsonschema<2.7,>=2.6 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting requests>=2.19 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 1.5MB/s 
Collecting sympy>=1.3 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/dd/f6/ed485ff22efdd7b371d0dbbf6d77ad61c3b3b7e0815a83c89cbb38ce35de/sympy-1.3.tar.gz (5.9MB)
    100% |████████████████████████████████| 5.9MB 983kB/s 
Collecting networkx>=2.2 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip (1.7MB)
    100% |████████████████████████████████| 1.7MB 1.4MB/s 
Collecting numpy>=1.13 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/a6/6f/cb20ccd8f0f8581e0e090775c0e3c3e335b037818416e6fa945d924397d2/numpy-1.16.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 619kB/s 
Collecting psutil>=5 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/2f/b8/11ec5006d2ec2998cb68349b8d1317c24c284cf918ecd6729739388e4c56/psutil-5.6.1.tar.gz (427kB)
    100% |████████████████████████████████| 430kB 2.0MB/s 
Collecting scipy!=0.19.1,>=0.19 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/dd/6c/ccf7403d14f0ab0f20ce611696921f204f4ffce99a4fd383c892a6a7e9eb/scipy-1.2.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.3MB)
    100% |████████████████████████████████| 27.3MB 471kB/s 
Collecting marshmallow-polyfield<4,>=3.2 (from qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/fa/ba/6406b8cce3e42b2838d234310c3605627083bbb8f71dcc312c616480fe92/marshmallow_polyfield-3.2-py2.py3-none-any.whl
Collecting cryptography>=1.3 (from requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/12/cd/f2c4dac6e48add01d4575e8fd8ca9a16f4236afe321e6e5ffdc7a4725b55/cryptography-2.6.1-cp34-abi3-macosx_10_6_intel.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 999kB/s 
Collecting ntlm-auth>=1.0.2 (from requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/8e/5b/4047779fb456b0de503c4acb7b166becf2567efb772abb53998440791d3c/ntlm_auth-1.2.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.19->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 1.1MB/s 
Collecting idna<2.9,>=2.5 (from requests>=2.19->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 976kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.19->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.5MB/s 
Collecting certifi>=2017.4.17 (from requests>=2.19->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 1.4MB/s 
Collecting mpmath>=0.19 (from sympy>=1.3->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz (512kB)
    100% |████████████████████████████████| 522kB 1.8MB/s 
Collecting decorator>=4.3.0 (from networkx>=2.2->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 1.8MB/s 
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/6b/af/e39e89ecbfb676c6aa5855b1795bb207f4005187495c8d40e26b5fb51bfa/cffi-1.12.2-cp37-cp37m-macosx_10_9_x86_64.whl (168kB)
    100% |████████████████████████████████| 174kB 2.0MB/s 
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit_terra==0.7.1->qiskit)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 2.3MB/s 
Installing collected packages: marshmallow, urllib3, idna, chardet, certifi, requests, six, asn1crypto, pycparser, cffi, cryptography, ntlm-auth, requests-ntlm, pillow, ply, jsonschema, mpmath, sympy, decorator, networkx, numpy, psutil, scipy, marshmallow-polyfield, qiskit-terra, qiskit-aer, qiskit-ignis, qiskit
  Running setup.py install for pycparser ... done
  Running setup.py install for mpmath ... done
  Running setup.py install for sympy ... done
  Running setup.py install for networkx ... done
  Running setup.py install for psutil ... done
  Running setup.py install for qiskit ... done
Successfully installed asn1crypto-0.24.0 certifi-2019.3.9 cffi-1.12.2 chardet-3.0.4 cryptography-2.6.1 decorator-4.4.0 idna-2.8 jsonschema-2.6.0 marshmallow-2.19.2 marshmallow-polyfield-3.2 mpmath-1.1.0 networkx-2.2 ntlm-auth-1.2.0 numpy-1.16.2 pillow-5.4.1 ply-3.11 psutil-5.6.1 pycparser-2.19 qiskit-0.8.0 qiskit-aer-0.1.1 qiskit-ignis-0.1.0 qiskit-terra-0.7.1 requests-2.21.0 requests-ntlm-1.1.0 scipy-1.2.1 six-1.12.0 sympy-1.3 urllib3-1.24.1
IGOR-3:~ igor$ 
```

**Comment by daveshen2019** [comment]
thanks.  it turns out python3.7 works.  it is the qiskit0.8 not work well for me.  i revert qiskit back to 0.7.0 and it worked.

**Comment by imv7** [comment]
Yeah (＾ｰ^)ノ, there are multiple command installed
