### ISSUE TITLE
Schema validation get thrown for empty circuit

### ISSUE THREAD

**Issue by ninofiliu** [Qiskit/qiskit-metapackage#209]
### Informations

- **Qiskit version**: 0.1.1
- **Python version**: 3.6.7
- **Operating system**: Linux 4.15.0 Ubuntu

### What is the current behavior?

I am building an *"empty circuit"* - a circuit with no measurement, no barrier, no gate, only a 1-bit quantum register whose vector state I want to print. `execute` fails on it because of schema validation, but if I add one gate, the error is gone. It looks more like an easily resolvable bug than a feature.

### Steps to reproduce the problem

This program creates the minimal circuit, but throws the error below upon `execute`:

```python
import qiskit as q

qr = q.QuantumRegister(1)
qc = q.QuantumCircuit(qr)
# uncomment me to make the error go away!
# qc.x(qr[0])
print(qc.draw())

sv_backend = q.BasicAer.get_backend('statevector_simulator')
sv_result = q.execute(qc, sv_backend).result()
print(sv_result.get_statevector(qc))
```

```
         
q0_0: |0>
         
qiskit.qobj._schema_validation._SummaryValidationError: 'Original message too long to be useful: {\'qobj_id\': \'f684ad2f-45f8-48ad-a45b-60435b516e26\', \'config\': {\'shots\': 1024, \'memory_slots\': 0, \'max_credits\': 10, \'memory\': False, \'n_qubits\': 1}, \'experiments\': [{\'instructions\': [], \'header\': {\'n_qubits\': 1, \'memory_slots\': 0, \'qubit_labels\': [[\'q0\', 0]], \'clbit_labels\': [], \'qreg_sizes\': [[\'q0\', 1]], \'creg_sizes\': [], \'name\': \'circuit0\', \'compiled_circuit_qasm\': \'OPENQASM 2.0;\\ninclude "qelib1.inc";\\nqreg q0[1];\\n\'}, \'config\': {\'memory_slots\': 0, \'n_qubits\': 1}}], \'header\': {\'backend_name\': \'statevector_simulator\'}, \'type\': \'QASM\', \'schema_version\': \'1.0.0\'} is not valid under any of the given schemas\n\nFailed validating \'oneOf\' in schema:\n    {\'$schema\': \'http://json-schema.org/draft-04/schema#\',\n     \'definitions\': {\'bfunc\': {\'properties\': {\'mask\': {\'type\': \'string\'},\n                                              \'memory\': {\'minimum\': 0,\n                                                         \'type\': \'integer\'},\n                                              \'name\': {\'enum\': [\'bf[...]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./simplest.py", line 9, in <module>
    sv_result = q.execute(qc, sv_backend).result()
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/tools/compiler.py", line 110, in execute
    return backend.run(qobj, **kwargs)
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/providers/builtinsimulators/statevector_simulator.py", line 125, in run
    return super().run(qobj, backend_options=backend_options)
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/providers/builtinsimulators/qasm_simulator.py", line 383, in run
    job.submit()
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/providers/builtinsimulators/simulatorsjob.py", line 70, in submit
    validate_qobj_against_schema(self._qobj)
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/qobj/_validation.py", line 23, in validate_qobj_against_schema
    err_msg='Qobj failed validation. '
  File "/home/nino/.local/lib/python3.6/site-packages/qiskit/qobj/_schema_validation.py", line 148, in validate_json_against_schema
    raise newerr
qiskit.qobj._schema_validation.SchemaValidationError: 'Qobj failed validation. Set Qiskit log level to DEBUG for further information.'
```

### What is the expected behavior?

```
         ┌───┐
q0_0: |0>┤ X ├
         └───┘
[1.+0.j 0.+0.j]
```

### Suggested solutions

There seems to be an invalid JSON schema somewhere that throws an error upon seeing an empty circuit, but I don't think empty circuits should be invalid. I even think that they're useful, as they provide a hello-world-like introductory case.

**Comment by ajavadia** [comment]
This has been fixed on master, the new release will not have this problem.
