### ISSUE TITLE
memoryError installing qiskit

### ISSUE THREAD

**Issue by andysc** [Qiskit/qiskit-metapackage#273]
### Informations

- **Qiskit version 0.10.0**:
- **Python version 3.5.2 **:
- **Operating system Ubuntu 16.04 LTS **:

### What is the current behavior?
'pip install qiskit' fails part way through installation with a 'memoryError' exception.

```
andy@sm:~$ pip install qiskit
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/80/e6/8b0b5a0e75d0a05060ce16a6e986051e9ee60c3ff58ff1088c983fc9aaea/qiskit-0.10.1.tar.gz
Collecting qiskit_terra==0.8.0 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/4e/41/2717ba8f8f636c7e78a8c1cb60ad84847a53bdbd5e0a4b06573b45542c35/qiskit_terra-0.8.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting qiskit-aer==0.2.0 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/e7/00/53441f06312a44c78b8d99ab84bb5e065a8455a3fc39642318d9c5a6f65b/qiskit_aer-0.2.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting qiskit-ibmq-provider==0.2.2 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/5f/46/5d950ad9ca8db2029104438967c6a29f66645a23fd8e8764e7df01f1dbcf/qiskit-ibmq-provider-0.2.2.tar.gz
Collecting qiskit-ignis==0.1.1 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/6e/4e/77230b3a51a864fd54c2ef7b6a0d417063cf4b18943ce8fcd45e15f74f3e/qiskit_ignis-0.1.1-py3-none-any.whl
Collecting qiskit-aqua==0.5.0 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/36/ec/7f265fb26b19e68deefc879e4642ca0618f5551d7b5765049562ad9824e5/qiskit_aqua-0.5.0-py3-none-any.whl
Collecting qiskit-chemistry==0.5.0 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/41/35/6b10aa3ea2fbe1b64cb0c3b2eaecb23cff044b574b151e8adc9ab9fbfe9a/qiskit_chemistry-0.5.0-py3-none-any.whl
Collecting psutil>=5 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/c6/c1/beed5e4eaa1345901b595048fab1c85aee647ea0fc02d9e8bf9aceb81078/psutil-5.6.2.tar.gz
Collecting marshmallow<3,>=2.17.0 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/bc/b4/f54f8533aad0645431bfda2cc3d20913a305779c80f8cb71229e8b615c5b/marshmallow-2.19.2-py2.py3-none-any.whl
Collecting marshmallow-polyfield<4,>=3.2 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/fa/ba/6406b8cce3e42b2838d234310c3605627083bbb8f71dcc312c616480fe92/marshmallow_polyfield-3.2-py2.py3-none-any.whl
Collecting pylatexenc>=1.4 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/54/ea/8e394f28d532f86241c77ecb8701e51973151059528de028a18c35249e8d/pylatexenc-1.4.tar.gz
Collecting sympy>=1.3 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/21/21/f4105795ca7f35c541d82c5b06be684dd2f5cb4f508fb487cd7aea4de776/sympy-1.4-py2.py3-none-any.whl
Collecting networkx>=2.2 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip
Collecting ply>=3.10 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting scipy>=1.0 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/f0/30/526bee2ce18c066f9ff13ba89603f6c2b96c9fd406b57a21a7ba14bf5679/scipy-1.2.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pillow>=4.2.1 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/de/62/6358ccd27b9e340affaa29e3e678b5d93a4b17f6bd7533fd6e6e87930b12/Pillow-6.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy>=1.13 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/f6/f3/cc6c6745347c1e997cc3e58390584a250b8e22b6dfc45414a7d69a3df016/numpy-1.16.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting jsonschema<2.7,>=2.6 (from qiskit_terra==0.8.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting requests>=2.19 (from qiskit-ibmq-provider==0.2.2->qiskit)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting requests-ntlm>=1.1.0 (from qiskit-ibmq-provider==0.2.2->qiskit)
  Using cached https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
Collecting websockets<8,>=7 (from qiskit-ibmq-provider==0.2.2->qiskit)
  Using cached https://files.pythonhosted.org/packages/f5/e2/569b96cf3cd4e7e4aad036282c6fc61124de70ca976fb0cf86c2a89633a3/websockets-7.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pyeda; sys_platform != "win32" (from qiskit-aqua==0.5.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/01/29/b6ce038a75409239db8762b4744c8b53eb62e0b6240ece1c2969a7250206/pyeda-0.28.0.tar.gz
Collecting scikit-learn>=0.20.0 (from qiskit-aqua==0.5.0->qiskit)
  Using cached https://files.pythonhosted.org/packages/3c/0b/fe1f5e349f9a31e47a30b834be4f668c4bf100c79cf564284fb04f14f381/scikit_learn-0.21.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting fastdtw (from qiskit-aqua==0.5.0->qiskit)
  Downloading https://files.pythonhosted.org/packages/fa/ef/a4cf2d72518b5fccd30284ba4d431fdb6266f72e75702ff05fd7c00b0b63/fastdtw-0.3.2.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 4.2MB/s 
Collecting torch; sys_platform != "win32" (from qiskit-aqua==0.5.0->qiskit)
  Downloading https://files.pythonhosted.org/packages/56/9b/a241f6e3d1df013e65e0b03b17e46bd9517036cd9ba9d8cb9384df396e3b/torch-1.1.0-cp35-cp35m-manylinux1_x86_64.whl (676.9MB)
    99% |████████████████████████████████| 676.9MB 38.8MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/serialize.py", line 80, in dumps
    data, separators=(",", ":"), sort_keys=True,
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

### Steps to reproduce the problem
```
alias python=python3
alias pip=pip3

pip install qiskit
```
### What is the expected behavior?

qiskit installed correctly with no fatal errors

**Comment by mtreinish** [comment]
This technically isn't directly an issue with qiskit., but one of aqua's dependencies torch. I also had this problem on one of my small test VMs. Torch pulls down a huge wheel and requires a ton of ram (which is likely why you got a MemoryError there, because it consumed all your free memory) to install. But, we really shouldn't force installing torch because of all these problems.

The plan is to make torch optional, and not try to install it by default. I've had a patch up to do this for a few days: https://github.com/Qiskit/qiskit-aqua/pull/523 once that merges there will be a point release to include that change.
