### ISSUE TITLE
Installing qiskit on RPiv3 (Balena docker container) errors

### ISSUE THREAD

**Issue by ajlennon** [Qiskit/qiskit-metapackage#278]
### Informations

- **Qiskit version**:

0.10.1

- **Python version**:

Python 3.5.7

- **Operating system**:

Linux - Building a Docker container via Balena.io

Base image is:

```
FROM balenalib/raspberrypi3-python:3-stretch-run
```

[image link](https://hub.docker.com/r/balenalib/raspberrypi3-python/)

### What is the current behavior?

pip tries to install qiskit. Then tries to install qiskit-terra dependency. 

This fails as cython seems to expect to see some qiskit files

```
ajlennon@ajlennon-VirtualBox:~/git/does-rpi3-qiskit$ DEBUG=1 balena deploy does-rpi3-qiskit --logs --source . --emulated --build
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   Failed to resolve project: 
[Debug]   AggregateError of:
[Debug]       Error: ENOENT: no such file or directory, open '/home/ajlennon/git/does-rpi3-qiskit/docker-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '/home/ajlennon/git/does-rpi3-qiskit/docker-compose.yaml'
[Info]    Creating default composition with source: /home/ajlennon/git/does-rpi3-qiskit
[Debug]   Creating project...
[Info]    Building for armv7hf/raspberrypi3
[Build]   Building services...
[Build]   main Preparing...
[Info]    Emulation is enabled
[Debug]   Found build tasks:
[Debug]       main: build [.]
[Debug]   Resolving services with [raspberrypi3|armv7hf]
[Debug]   Found project types:
[Debug]       main: Dockerfile.template
[Debug]   Prepared tasks; building...
[Build]   main Step 1/12 : FROM balenalib/raspberrypi3-python:3-stretch-run
[Build]   main  ---> ab9986f06166
[Build]   main Step 2/12 : COPY [".balena/qemu-execve","/tmp/qemu-execve"]
[Build]   main  ---> Using cache
[Build]   main  ---> 34010550d25e
[Build]   main Step 3/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","install_packages libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6"]
[Build]   main  ---> Using cache
[Build]   main  ---> e020899e4da6
[Build]   main Step 4/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","install_packages build-essential"]
[Build]   main  ---> Using cache
[Build]   main  ---> e612e2333a4b
[Build]   main Step 5/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","pip install Cython"]
[Build]   main  ---> Using cache
[Build]   main  ---> 516b77535f9f
[Build]   main Step 6/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","pip install --upgrade pip"]
[Build]   main  ---> Using cache
[Build]   main  ---> 66087f99bf1c
[Build]   main Step 7/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","python -V"]
[Build]   main  ---> Running in 8e0e8efb99fe
[Build]   main Python 3.5.7
[Build]   main Removing intermediate container 8e0e8efb99fe
[Build]   main  ---> 748e8fbad793
[Build]   main Step 8/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","pip install qiskit"]
[Build]   main  ---> Running in dafdfb84f08d
[Build]   main Collecting qiskit
[Build]   main   Downloading https://files.pythonhosted.org/packages/80/e6/8b0b5a0e75d0a05060ce16a6e986051e9ee60c3ff58ff1088c983fc9aaea/qiskit-0.10.1.tar.gz
[Build]   main Collecting qiskit_terra==0.8.0 (from qiskit)
[Build]   main   Downloading https://files.pythonhosted.org/packages/fc/a3/964b0d29349b88682df937becab123da7d63645b1a54f0db098617923404/qiskit-terra-0.8.0.tar.gz (565kB)
[Build]   main     ERROR: Complete output from command python setup.py egg_info:
[Build]   main     ERROR: Traceback (most recent call last):
[Build]   main       File "<string>", line 1, in <module>
[Build]   main       File "/tmp/pip-install-eamktlwo/qiskit-terra/setup.py", line 109, in <module>
[Build]   main         ext_modules=cythonize(EXT_MODULES),
[Build]   main       File "/usr/local/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
[Build]   main         aliases=aliases)
[Build]   main       File "/usr/local/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
[Build]   main         for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
[Build]   main       File "/usr/local/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
[Build]   main         raise ValueError(error_msg)
[Build]   main     ValueError: 'qiskit/transpiler/passes/mapping/cython/stochastic_swap/utils.pyx' doesn't match any files
[Build]   main     ----------------------------------------
[Build]   main ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-eamktlwo/qiskit-terra/
[Build]   Built 1 service in 0:21
[Error]   Deploy failed
Error: The command '/tmp/qemu-execve -execve /bin/sh -c pip install qiskit' returned a non-zero code: 1
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:178:23)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/usr/lib/node_modules/balena-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:137:22)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

### Steps to reproduce the problem

A bit complicated unfortunately. You need to follow the Balena getting started instructions

https://www.balena.io/docs/learn/getting-started/raspberrypi3/python/

Then check out my repo branch and commit to  a Balena repo endpoint as detailed above

https://github.com/DynamicDevices/does-rpi3-qiskit/tree/ajl/not-working-1

### What is the expected behavior?

Qiskit should install without error.

### Suggested solutions

Going to try an older version...

**Comment by nonhermitian** [comment]
I believe it is because the .pyx files are not included in the package data.

**Comment by ajlennon** [comment]
Just trying qiskit_terra==0.7.2 - it seems to be getting further. Will update shortly

**Comment by nonhermitian** [comment]
Because that does not have the Cython code that is causing you problems.

**Comment by ajlennon** [comment]
I'm a #noob with Python. It errors if I don't have Cython present...

**Comment by mtreinish** [comment]
@nonhermitian ah, yeah that's a good catch we don't include the pyx files in the sdist for terra. We should add that into the MANIFSET.in before the next bugfix release so people can actually build it from source. There are the generated cpp files in the sdist, but we'll fail on the cythonize() call in the setup.py without the pyx files.

**Comment by ajlennon** [comment]
Thanks guys - when are you going to push a release that will work for me?

**Comment by ajlennon** [comment]
You seem to have the same problem with qiskit

```
ValueError: 'qiskit/transpiler/passes/mapping/cython/stochastic_swap/utils.pyx' doesn't match any files
```
