### ISSUE TITLE
Error while installing Qiskit 0.13.0

### ISSUE THREAD

**Issue by SamMondal** [Qiskit/qiskit-metapackage#689]
Hello,
While running "pip install qiskit" within the conda environment for qiskit, I get the error detailed below. Could you please suggest what should I do? (latest version of anaconda=2019.10)

```
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/9e/2d/4c09bc1292a3be92f8c003b8491215ac9a0d81b014384e95a659a58ddf57/qiskit-0.13.0.tar.gz
Collecting qiskit-terra==0.10.0
  Using cached https://files.pythonhosted.org/packages/4e/86/180961c6ae2fecf521c5ea4246a3a3f52e9cbfed022c537733cc5203c228/qiskit-terra-0.10.0.tar.gz
Collecting qiskit-aer==0.3.2
  Using cached https://files.pythonhosted.org/packages/a8/46/11edbd99d7b732e63a542623109f394f17d9ad4051ddeb1e2dd9f36d1aac/qiskit-aer-0.3.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/sam/softwares/anaconda3/envs/qiskitenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8153ylk0/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8153ylk0/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8153ylk0/qiskit-aer/pip-egg-info
         cwd: /tmp/pip-install-8153ylk0/qiskit-aer/
    Complete output (113 lines):
    Collecting scikit-build
      Using cached https://files.pythonhosted.org/packages/8a/b5/c6ca60421991c22e69b9a950b0d046e06d714f79f7071946ab885c7115fb/scikit_build-0.10.0-py2.py3-none-any.whl
    Requirement already satisfied: setuptools>=28.0.0 in /home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages (from scikit-build) (41.6.0.post20191030)
    Requirement already satisfied: wheel>=0.29.0 in /home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages (from scikit-build) (0.33.6)
    Collecting packaging
      Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
    Collecting six
      Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
    Collecting pyparsing>=2.0.2
      Using cached https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl
    Installing collected packages: six, pyparsing, packaging, scikit-build
    Successfully installed packaging-19.2 pyparsing-2.4.5 scikit-build-0.10.0 six-1.13.0
    Searching for cmake
    Reading https://pypi.org/simple/cmake/
    Downloading https://files.pythonhosted.org/packages/0a/f5/3212616a15b4112d7ad075a407f007eac2cac59292a9d973f2ee7e3c4068/cmake-3.13.2.post1.tar.gz#sha256=b45cc0f56f3f5705f4b4678ecf1f82e09c852c01cb3ffff43effdf8ffa323b1d
    Best match: cmake 3.13.2.post1
    Processing cmake-3.13.2.post1.tar.gz
    Writing /tmp/easy_install-js4pj4s3/cmake-3.13.2.post1/setup.cfg
    Running cmake-3.13.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-js4pj4s3/cmake-3.13.2.post1/egg-dist-tmp-kch16ylg
    Traceback (most recent call last):
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-js4pj4s3/cmake-3.13.2.post1/setup.py", line 32, in <module>
        name='qiskit-aer',
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8153ylk0/qiskit-aer/setup.py", line 31, in <module>
        setup(
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 456, in setup
        return upstream_setup(*args, **kw)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-js4pj4s3/cmake-3.13.2.post1/setup.py", line 32, in <module>
        name='qiskit-aer',
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "/home/sam/softwares/anaconda3/envs/qiskitenv/lib/python3.8/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by glassnotes** [comment]
The exact same thing is happening to me; I tried in fresh environments on two different machines (one running CentOs 7.3.1611, the other running Ubuntu 18.04). 

I'm using:
 - Python 3.8.0
 - conda 4.7.12
 
I was able to make some progress by running `pip install cmake`, but then it got stuck (on both machines) trying to install pyscf and linking to BLAS libraries. Not sure if it is an issue with qiskit at that point though.

**Comment by glassnotes** [comment]
Update: it seems that it is an issue when using Python 3.8. The process works just fine in 3.7.5.

**Comment by amacgillivray** [comment]
I've documented (using the bug-issue format) the same problem in #705.  The issue will be addressed by documentation changes (see #660).

**Comment by SamMondal** [comment]
Took me a while to get back. Thank you for the suggestions, qiskit is now properly installed with "python=3.7.5". Thanks again!

**Comment by mtreinish** [comment]
Qiskit 0.15.0 is out now and includes support for python 3.8. I'm going to close this issue now, please feel free to reopen it if I'm missing something.

**Comment by mrostamii** [comment]
I have the same problem on Windows 10 x64.  
`Python 3.7.4` on `virtualenv`. 

Any solution?
