### ISSUE TITLE
Unable to Install to New Pip Env (TypeError)

### ISSUE THREAD

**Issue by amacgillivray** [Qiskit/qiskit-metapackage#705]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3
- **Operating system**: Ubuntu 18.04.3 (LTS) x64

### What is the current behavior?

Installing Anaconda3, creating a new pip environment, activating and using the environment, and then attempting to install using `pip install qiskit` fails at after collecting `https://files.pythonhosted.org/packages/a8/46/11edbd99d7b732e63a542623109f394f17d9ad4051ddeb1e2dd9f36d1aac/qiskit-aer-0.3.2.tar.gz`. 

The error is unique from #389 (GCC-related) and #696 (OSX, numpy-related).  The appears identical to #689.

--- 

```
(test) user@user-gp-nyc-002:~$ pip install qiskit
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/9e/2d/4c09bc1292a3be92f8c003b8491215ac9a0d81b014384e95a659a58ddf57/qiskit-0.13.0.tar.gz
Collecting qiskit-terra==0.10.0
  Using cached https://files.pythonhosted.org/packages/4e/86/180961c6ae2fecf521c5ea4246a3a3f52e9cbfed022c537733cc5203c228/qiskit-terra-0.10.0.tar.gz
Collecting qiskit-aer==0.3.2
  Using cached https://files.pythonhosted.org/packages/a8/46/11edbd99d7b732e63a542623109f394f17d9ad4051ddeb1e2dd9f36d1aac/qiskit-aer-0.3.2.tar.gz

ERROR: Command errored out with exit status 1:
     command: ~/anaconda3/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1qh9fii4/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1qh9fii4/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1qh9fii4/qiskit-aer/pip-egg-info
         cwd: /tmp/pip-install-1qh9fii4/qiskit-aer/
    Complete output (101 lines):
    Searching for cmake
    Reading https://pypi.org/simple/cmake/
    Downloading https://files.pythonhosted.org/packages/0a/f5/3212616a15b4112d7ad075a407f007eac2cac59292a9d973f2ee7e3c4068/cmake-3.13.2.post1.tar.gz#sha256=b45cc0f56f3f5705f4b4678ecf1f82e09c852c01cb3ffff43effdf8ffa323b1d
    Best match: cmake 3.13.2.post1
    Processing cmake-3.13.2.post1.tar.gz
    Writing /tmp/easy_install-5gf5ixot/cmake-3.13.2.post1/setup.cfg
    Running cmake-3.13.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5gf5ixot/cmake-3.13.2.post1/egg-dist-tmp-jb1c2y06
    Traceback (most recent call last):
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-5gf5ixot/cmake-3.13.2.post1/setup.py", line 32, in <module>
        name='qiskit-aer',
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "~/anaconda3/envs/test/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "~/anaconda3/envs/test/lib/python3.8/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1qh9fii4/qiskit-aer/setup.py", line 31, in <module>
        setup(
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 456, in setup
        return upstream_setup(*args, **kw)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "~/anaconda3/envs/test/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "~/anaconda3/envs/test/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-5gf5ixot/cmake-3.13.2.post1/setup.py", line 32, in <module>
        name='qiskit-aer',
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "~/anaconda3/envs/test/lib/python3.8/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "~/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "~/anaconda3/envs/test/lib/python3.8/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

---

I was able to install the package when running pip from the *base* environment, but not from *test*.  Notably, the base environment is running Python 3.73, while test is running 3.80 (again, identical to #689 .

### Steps to reproduce the problem

Problem occurred while following [the official installation documentation](https://qiskit.org/documentation/install.html#install).

* Install Anaconda3
* run `conda create -n test python=3`
* run `pip install qiskit`

### What is the expected behavior?

Qiskit should successfully install when following instructions provided by the official documentation.

### Suggested solutions

None at this time.

**Comment by amacgillivray** [comment]
Closing: Looks like this will be addressed in the documentation updates discussed in #660 (more information about why the error has happened is also available there - specifically, the new environment is created with the latest version of Python, which may not be compatible with qiskit).
