### ISSUE TITLE
Pip installing on python 3.8 requires libcint

### ISSUE THREAD

**Issue by HamedMP** [Qiskit/qiskit-metapackage#759]
### Informations

- **Qiskit version**: 0.14.0
- **Python version**: 3.8
- **Operating system**: MacOS Catalina 10.15.1

### What is the current behavior?

Tried installing `qiskit` as described in the docs by creating a new environment with `conda` and running `pip install qiskit`, got the following error:

```bash
$ pip install qiskit
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/59/2d/563ea183a9462f1300e861796535405d0fca8616b6db849488eac225893b/qiskit-0.14.0.tar.gz
Collecting qiskit-terra==0.11.0
  Using cached https://files.pythonhosted.org/packages/ca/19/e8fb3786b8173d2f0b7a1936c028af2eaf0e194541959b778530ecde9d01/qiskit-terra-0.11.0.tar.gz
Collecting qiskit-aer==0.3.4
  Using cached https://files.pythonhosted.org/packages/0b/4a/5cbe3ad58941408b51156d9793549f17aa91257fc20a4d76b6e5209dc86f/qiskit-aer-0.3.4.tar.gz
Collecting qiskit-ibmq-provider==0.4.4
  Using cached https://files.pythonhosted.org/packages/7f/91/1236cd0da9552744aae173792c44a7a1611436f3a8156b62604aab2e67e5/qiskit_ibmq_provider-0.4.4-py3-none-any.whl
Collecting qiskit-ignis==0.2.0
  Using cached https://files.pythonhosted.org/packages/78/f2/f4f89c65d2c13f473092f7e800519836611ddeeaab8d4591a70555b26a37/qiskit_ignis-0.2.0-py3-none-any.whl
Collecting qiskit-aqua==0.6.1
  Using cached https://files.pythonhosted.org/packages/47/2b/632c195974804d17dca01554caa013dd0c3023f4e4e6b91213c3381ce514/qiskit_aqua-0.6.1-py3-none-any.whl
Collecting jsonschema>=2.6
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting marshmallow<4,>=3
  Using cached https://files.pythonhosted.org/packages/6e/76/01224f14737627166b94eb3bf0e334372c014edca781e39db320ce977755/marshmallow-3.3.0-py2.py3-none-any.whl
Collecting marshmallow_polyfield<6,>=5.7
  Using cached https://files.pythonhosted.org/packages/d7/6c/416e7e529d03362bb57bb4be16a0bb1ada6325b12adf3e31fec4c10ef1b1/marshmallow-polyfield-5.7.tar.gz
Requirement already satisfied: numpy>=1.13 in /Users/hanel/anaconda3/envs/qpy/lib/python3.8/site-packages (from qiskit-terra==0.11.0->qiskit) (1.17.4)
Collecting ply>=3.10
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting psutil>=5
  Using cached https://files.pythonhosted.org/packages/73/93/4f8213fbe66fc20cb904f35e6e04e20b47b85bee39845cc66a0bcf5ccdcb/psutil-5.6.7.tar.gz
Collecting scipy>=1.0
  Using cached https://files.pythonhosted.org/packages/90/d2/44b70a930ad28da8f65d8c294ac88b20f561e5d650b85efea80381566db1/scipy-1.4.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting sympy>=1.3
  Using cached https://files.pythonhosted.org/packages/ce/5b/acc12e3c0d0be685601fc2b2d20ed18dc0bf461380e763afc9d0a548deb0/sympy-1.5.1-py2.py3-none-any.whl
Collecting dill>=0.3
  Using cached https://files.pythonhosted.org/packages/c7/11/345f3173809cea7f1a193bfbf02403fff250a3360e0e118a1630985e547d/dill-0.3.1.1.tar.gz
Collecting networkx>=2.2
  Using cached https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl
Collecting websockets<8,>=7
  Using cached https://files.pythonhosted.org/packages/ba/60/59844a5cef2428cb752bd4f446b72095b1edee404a58c27e87cd12a141e2/websockets-7.0.tar.gz
Collecting requests>=2.19
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting requests-ntlm>=1.1.0
  Using cached https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
Collecting nest-asyncio!=1.1.0,>=1.0.0
  Using cached https://files.pythonhosted.org/packages/52/01/55100e0dda328f2181b719bddc5af0a24487de81038747d676d5be7ef879/nest_asyncio-1.2.1-py3-none-any.whl
Requirement already satisfied: setuptools>=40.1.0 in /Users/hanel/anaconda3/envs/qpy/lib/python3.8/site-packages (from qiskit-ignis==0.2.0->qiskit) (42.0.2.post20191203)
Collecting h5py
  Using cached https://files.pythonhosted.org/packages/7a/1d/e64957225e693f27f2c8024923449830fc1d1ca513e7675fb10939dc2caa/h5py-2.10.0-cp38-cp38-macosx_10_9_x86_64.whl
Collecting cvxopt
  Using cached https://files.pythonhosted.org/packages/00/02/13657bcd12d93f53b64a19b68d204f43d5f3247c29287c9eaeefcfa58fb9/cvxopt-1.2.3.tar.gz
Collecting quandl
  Downloading https://files.pythonhosted.org/packages/07/ab/8cd479fba8a9b197a43a0d55dd534b066fb8e5a0a04b5c0384cbc5d663aa/Quandl-3.5.0-py2.py3-none-any.whl
Collecting scikit-learn>=0.20.0
  Using cached https://files.pythonhosted.org/packages/5a/5b/520ed622a1896ac320c19fe8f32ae13258ec72d884e8c6c9753e2b60197e/scikit_learn-0.22.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting dlx
  Downloading https://files.pythonhosted.org/packages/54/c0/b8fb5bb727e983b6f5251433ef941b48f38c65bb0bd6ec509e9185bcd406/dlx-1.0.4.tar.gz
Collecting pyscf; sys_platform != "win32"
  Using cached https://files.pythonhosted.org/packages/b5/f4/ed70c61541d134c1a6c78cc1723ceab9144ce7a8cf60344862151c0f492e/pyscf-1.7.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/hanel/anaconda3/envs/qpy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/__/hyt6c9lx4czd3n3_b4_0gty40000gn/T/pip-install-9q4z3mqk/pyscf/setup.py'"'"'; __file__='"'"'/private/var/folders/__/hyt6c9lx4czd3n3_b4_0gty40000gn/T/pip-install-9q4z3mqk/pyscf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/__/hyt6c9lx4czd3n3_b4_0gty40000gn/T/pip-install-9q4z3mqk/pyscf/pip-egg-info
         cwd: /private/var/folders/__/hyt6c9lx4czd3n3_b4_0gty40000gn/T/pip-install-9q4z3mqk/pyscf/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/__/hyt6c9lx4czd3n3_b4_0gty40000gn/T/pip-install-9q4z3mqk/pyscf/setup.py", line 354, in <module>
        raise RuntimeError
    RuntimeError
    Using MKL library in /Users/hanel/anaconda3/envs/qpy/lib
    ****************************************************************
    *** WARNING: libcint library not found.
    * You can download libcint library from http://github.com/sunqm/libcint
    * May need to set PYSCF_INC_DIR if libcint library was not installed in the
    * system standard install path (/usr, /usr/local, etc). Eg
    *   export PYSCF_INC_DIR=/path/to/libcint:/path/to/other/lib
    ****************************************************************
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Suggested solutions

It's fixed when I switched the `python` version from 3.8 to 3.7 with:

```bash
conda install python=3.7
```

**Comment by schwarmco** [comment]
Python 3.8 isn't supported yet, more info on that here: https://github.com/Qiskit/qiskit/issues/758#issuecomment-570346647 and here: https://github.com/Qiskit/qiskit/issues/689

**Comment by nonhermitian** [comment]
This is also an issue with PySCF.  Closing since 3.8 support is not ready yet (almost).
