### ISSUE TITLE
scikit_learn failed

### ISSUE THREAD

**Issue by ChainCoderX** [Qiskit/qiskit-metapackage#905]
MacOS
cmd:  pip install qiskit

**Comment by ChainCoderX** [comment]
error:

Collecting scikit-learn>=0.20.0
  Downloading scikit_learn-0.22.2.post1-cp38-cp38-macosx_10_9_x86_64.whl (7.2 MB)
     |██████████████████████████████▌ | 6.9 MB 46 kB/s eta 0:00:08ERROR: Exception:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    local_path = unpack_url(
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
    return unpack_http_url(
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 158, in unpack_http_url
    from_path, content_type = _download_http_url(
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 15, in response_chunks
    for chunk in response.raw.stream(
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/anaconda3/envs/name_of_my_env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by ChainCoderX** [comment]
run the command  "pip install qiskit" again.
It works.

**Comment by nonhermitian** [comment]
This is a problem connecting to `host='files.pythonhosted.org',` to grab files.  This is not really a Qiskit issue.

**Comment by ChainCoderX** [comment]
got it.
Thank you.
